import React from 'react';
import '../css/post.css';

export default function Rationale() {
    return(
        <div className='container left-container' >
            <h1>Rhetorical Rationale</h1>
            <p><b>Genres:</b></p>
            <ol>
                <li>Blog post</li>
                <li>Infographic</li>
                <li>Demo of AI in practice</li>
            </ol>
            <ul>
                <li><b>Purpose:</b> I will be discussing the topic of ethics in artificial intelligence and machine learning. It can be controversial discussing the implementation of artificial intelligence as an aid in our everyday lives because of the ethical conflicts that can arise because of it. Examples of these may be: an autonomous vehicle crashing and killing passengers, security concerns of our data being collected to be processed by computers, or unemployment as a result of computers being able to do certain jobs. My stance will be that machine learning has more benefits than harm and I will address these topics in a responsible manner.</li>
                <li><b>Audience:</b> My two unique audiences that I intend to target will be people who have an ethical concern on the progression of technology in the current state, as well as people who may happen to stumble upon my articles when reading other articles on another site that displays articles. This is the case since my medium will be an online format. My audience will especially be grabbed when I mention their privacy and how their information is being collected by companies that they may not know about.</li>
                <li><b>Rhetorical Appeals:</b> I will have to establish a sense of ethos to my readers, since my audience will be comprised of people that have never met me. I will be using links to sources within my content and embedding them in my blog so people can quickly check the reliability of a source that I used. The aesthetic and completeness of my website will also create a sense of ethos as viewers will believe that I know what I am talking about since I created a website that is nice. They can gain a sense of trust in my ability with technology from the website, when they are reading about my opinion on technology. I will also include an about section that will talk about my background and further progress my credibility. I will use logos to logically explain my point of view on the topic but also address the concerns and arguments against my stance, to not seem one-sided. I will not need to using pathos on my audience, since it may seem like a manipulation technique on an ethical topic like this, but my topic will address things that may bring about emotions in people, such as death of people by computers. </li>
                <li><b>Modes and Media:</b> I will be creating a personal website to display my genres in a digital medium. I will be using 3 different modes to address the 3 different genres. I will have a blog that will be a text mode, I will have an infographic/poster that will be a visual format, and finally I will try to build an example of a machine learning use case on my website that people can try out and see an example of it in action. I think these three genres combine to show my audience a good representation of my stance, and can fit anyone who prefers either text, visual, or learning by doing. The blog will fit people more who prefer reading a casual format while the infographic will fit people more who do not want to invest their time in reading and would rather quickly glance to obtain the information on the topic. The model example will be suitable for people who have no idea how machine learning can apply in the real world so that they can gain a better understanding of it in action.</li>
                <li><b>Elements of Genres:</b> I will be using a casual and fun writing style in my blog to give a more entertaining appeal to people who enjoy reading blogs. I will ensure to include a few images in the blog as well to provide some more context and reference to what I will be talking about. I will be using a very simply and clean drawing style for my infographic, so that viewers are not overwhelmed by complex drawings on the poster. I will ensure to bold an emphasize the numbers in the infographic to ensure that the numbers catch the attention of viewers, so that they are interested in reading the whole poster. In the genre where I will be including a demo of artificial intelligence in practice, I will be making a brief statement that will explain what I am presenting. This will connect the demo to a real world use case for the readers and help them understand why artificial intelligence is so powerful.</li>
                <li><b>Style:</b> As a writer, I do not see myself as having a superior vocabulary, so I will using my strength to write a blog that anyone of any level can read in order to understand my point of view. I will be using an enthusiastic tone with a simple style that anyone can understand. However, one of my strengths is aesthetic design. I will be harnessing this strength through a beautifully designed website blog and an elegant infographic. I will using software that will allow me to create a nice design for the infographic that has colors that pop and also fit the theme of artificial intelligence.</li>
                <li><b>Design:</b> As a software engineer in my field of computer science, I will be building the website myself so I will ensure a simple and elegant design that fits the content that I provide. This can also provide a sense of ethos for me, since people can see that I have an idea of what I am doing. I will be coding the website from scratch by myself which will enable me full creative freedom with what I wish to present. I will be creating subtle animations and a uniform color scheme that will present a sense of credibility to my website.</li>
                <li><b>Sources:</b> Since this is a digital format, sources will be easy to incorporate. In my text I will including embedded links to sources, so that readers can reference a source that I used immediately while reading. This will give them the convenience of determining my credible as they read, so they will be interested to continue to read more, since it is just a click away.</li>
            </ul>
        </div>
    )
}